name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *' # Запуск каждый день в 03:00 (по UTC)
  workflow_dispatch: # Позволяет запускать скрипт вручную по кнопке

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешение на запись изменений в форк

    steps:
      - name: Sync repo with upstream
        run: gh repo sync ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
